### ISSUE TITLE
外置sd卡的写入操作权限

### ISSUE THREAD

**Issue by moter** [gongshoudao/SDcardScanner#1]
你这个对外置sd卡的写入全是只能是应用程序包名下。对于其他目录的写入有没有解决思路

**Comment by gongshoudao** [comment]
没有。高版本上系统禁止操作SD卡上的出公共目录和APP私有目录外的其它文件。Google这样做是有一定道理的，如果任何应用都能在removable的磁盘上的任何位置创建文件，那磁盘上的数据就会杂乱不堪。相信未来Google会在磁盘操作方面限制更多。比如Android6.0上的不能直接通过file:// uri访问非其他应用程序路径下的文件，必须使用FileProvider+授权方式实现。
